In [1]:
import pandas as pd
import numpy as np

In [2]:
sample_data = {
    "NDVI": [0.75, 0.42, 0.15, 0.67, None],
    "NDBI": [0.20, 0.55, 0.80, 0.30, 0.65],
    "LST": [28.5, 35.2, 41.8, 30.4, 38.7],
    "PopulationDensity": [1200, 4500, 8000, 2000, 6000],
    "Humidity": [65, 55, 40, 70, 50]
}

df = pd.DataFrame(sample_data)

df

   NDVI  NDBI   LST  PopulationDensity  Humidity
0  0.75  0.20  28.5               1200        65
1  0.42  0.55  35.2               4500        55
2  0.15  0.80  41.8               8000        40
3  0.67  0.30  30.4               2000        70
4   NaN  0.65  38.7               6000        50

In [3]:
df.isnull().sum()

NDVI                 1
NDBI                 0
LST                  0
PopulationDensity    0
Humidity             0
dtype: int64

In [4]:
def clean_data(df):

    print("Missing Values Before:")
    print(df.isnull().sum())

    numeric_cols = df.select_dtypes(include=np.number).columns

    for col in numeric_cols:
        df[col] = df[col].fillna(df[col].median())

    print("\nMissing Values After:")
    print(df.isnull().sum())

    return df

In [5]:
clean_df = clean_data(df)

clean_df

Missing Values Before:
NDVI                 1
NDBI                 0
LST                  0
PopulationDensity    0
Humidity             0
dtype: int64

Missing Values After:
NDVI                 0
NDBI                 0
LST                  0
PopulationDensity    0
Humidity             0
dtype: int64

    NDVI  NDBI   LST  PopulationDensity  Humidity
0  0.750  0.20  28.5               1200        65
1  0.420  0.55  35.2               4500        55
2  0.150  0.80  41.8               8000        40
3  0.670  0.30  30.4               2000        70
4  0.545  0.65  38.7               6000        50

In [6]:
clean_df.isnull().sum()

NDVI                 0
NDBI                 0
LST                  0
PopulationDensity    0
Humidity             0
dtype: int64