In [1]:
import pandas as pd
import numpy as np

In [6]:
data = {
    "Area": ["Zone A", "Zone B", "Zone C", "Zone D", "Zone E"],
    "Predicted_LST": [28.5, 33.2, 37.8, 42.1, 39.5]
}
df = pd.DataFrame(data)

df

     Area  Predicted_LST
0  Zone A           28.5
1  Zone B           33.2
2  Zone C           37.8
3  Zone D           42.1
4  Zone E           39.5

In [3]:
def classify_heat(lst):

    if lst < 30:
        return "Low Risk"

    elif lst < 35:
        return "Moderate Risk"

    elif lst < 40:
        return "High Risk"

    else:
        return "Extreme Hotspot"

In [7]:
df["Heat_Risk"] = df["Predicted_LST"].apply(classify_heat)

df

     Area  Predicted_LST        Heat_Risk
0  Zone A           28.5         Low Risk
1  Zone B           33.2    Moderate Risk
2  Zone C           37.8        High Risk
3  Zone D           42.1  Extreme Hotspot
4  Zone E           39.5        High Risk

In [8]:
df["Heat_Risk"].value_counts()

Heat_Risk
High Risk          2
Low Risk           1
Moderate Risk      1
Extreme Hotspot    1
Name: count, dtype: int64

In [9]:
extreme_hotspots = df[
    df["Heat_Risk"] == "Extreme Hotspot"
]

extreme_hotspots

     Area  Predicted_LST        Heat_Risk
3  Zone D           42.1  Extreme Hotspot

In [10]:
extreme_hotspots.to_csv(
    "../outputs/reports/extreme_hotspots.csv",
    index=False
)

print("Hotspots Saved Successfully")

Hotspots Saved Successfully