In [1]:
import pandas as pd

In [2]:
current_data = {
    "NDVI": [0.25],
    "NDBI": [0.70],
    "Predicted_LST": [41.0]
}

df = pd.DataFrame(current_data)

df

   NDVI  NDBI  Predicted_LST
0  0.25   0.7           41.0

In [3]:
print("Current Scenario")
df

Current Scenario

   NDVI  NDBI  Predicted_LST
0  0.25   0.7           41.0

In [4]:
scenario_1 = df.copy()

scenario_1["NDVI"] = 0.45

scenario_1

   NDVI  NDBI  Predicted_LST
0  0.45   0.7           41.0

In [5]:
scenario_1["Predicted_LST"] = (
    scenario_1["Predicted_LST"] - 3
)

scenario_1

   NDVI  NDBI  Predicted_LST
0  0.45   0.7           38.0

In [6]:
print("""
Scenario:

Increase Green Cover

NDVI:
0.25 → 0.45

Estimated LST Reduction:
41°C → 38°C
""")

Scenario:

Increase Green Cover

NDVI:
0.25 → 0.45

Estimated LST Reduction:
41°C → 38°C

In [7]:
scenario_2 = df.copy()

scenario_2["NDBI"] = 0.55

scenario_2["Predicted_LST"] = (
    scenario_2["Predicted_LST"] - 2
)

scenario_2

   NDVI  NDBI  Predicted_LST
0  0.25  0.55           39.0

In [8]:
print("""
Scenario:

Cool Roof Program

Built-up Heat Effect Reduced

Estimated Temperature Reduction:
41°C → 39°C
""")

Scenario:

Cool Roof Program

Built-up Heat Effect Reduced

Estimated Temperature Reduction:
41°C → 39°C